# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88444829d4438f096093ebd1f8caebf8fbe2f411849bfbc831e2ada09d1ef873964eb1f867f09fd809439309f8cfcc1094db7f6098a18ed9f51d8411f16d03b1

test:
  secret_key_base: ff160047b5c0ad27e1fa1f29da29d6993f440d31905f06bee0233a0fcb8044a24213e60a8e58c4038fb588a871b06c5f97c31a6a467f492e952e36e86dd485ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
